### ISSUE TITLE
How to represent a molecule with your work from a molecular SMILES?

### ISSUE THREAD

**Issue by hcji** [ZhaoningYu1996/HM-GNN#2]
Hi,

I m trying to train a model with my own data based on your work. but what I have is a list of molecular SMILES and the corresponding labels, for example:

```
x = ['CCCC', 'CCCO', 'CCCN' ...]
y = [1,1,0, ...]
```

your example datasets are preprocessed graph described by a list of files. Is there any function to convert molecular SMILES to the same format?

Thanks

**Comment by ZhaoningYu1996** [comment]
Hi hcji,

Thank you for your interest in our work.
We did not implement a SMILES version preprocessing. 
However, you can convert SMILES into .mol object first, then convert mol into networkx object.
In this way, you can use our functions to do the preprocessing.
You can refer to the code below as an example.
https://gist.github.com/fangkuoyu/dc785218e5d4d94c752e80f1aaba4fad

Best
