### ISSUE TITLE
 I report an error when I run the main file after using data_preprocess.py

### ISSUE THREAD

**Issue by qq543411419** [ZhaoningYu1996/HM-GNN#4]
Why do I report an error when I run the main file after using data_preprocess.py to get the pre-training file MUTAG.txt of mutag dataset

classes: 2
maximum node tag: 7
data: 188
188
[[2, 9, 30, 32, 35, 53, 78, 81, 115, 117, 125, 130, 142, 146, 150, 156, 161, 172, 182], [0, 10, 14, 21, 27, 38, 42, 54, 86, 88, 98, 102, 106, 133, 155, 165, 178, 179, 187], [6, 16, 19, 23, 55, 61, 63, 74, 80, 87, 97, 107, 110, 121, 126, 148, 162, 166, 173], [11, 22, 24, 34, 52, 57, 60, 68, 79, 83, 89, 109, 120, 135, 147, 149, 153, 159, 180], [1, 41, 43, 44, 46, 47, 49, 56, 84, 92, 101, 104, 113, 114, 119, 123, 124, 154, 170], [15, 17, 18, 20, 26, 59, 69, 75, 77, 93, 96, 103, 105, 128, 139, 140, 145, 174, 177], [5, 48, 58, 64, 66, 70, 72, 99, 122, 143, 144, 151, 152, 160, 164, 171, 183, 184, 185], [7, 12, 25, 29, 33, 37, 39, 45, 50, 67, 76, 82, 85, 95, 100, 108, 129, 132, 181], [3, 8, 13, 28, 36, 40, 62, 111, 112, 131, 136, 138, 141, 168, 169, 175, 176, 186], [4, 31, 51, 65, 71, 73, 90, 91, 94, 116, 118, 127, 134, 137, 157, 158, 163, 167]]
epochs:   0%|        
已放弃 (核心已转储)

**Comment by ZhaoningYu1996** [comment]
Hi,

Could you show me a detailed error message?
