### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Yang1806** [ZhaoningYu1996/HM-GNN#6]
Hello! I have a question about the code:
In data_loader.py line 42-44:

        with open('dataset/%s/node_labels.txt' % (data), 'r') as f:
            nl = f.readlines()
        node_labels = [int(i[-2]) for i in nl]

Why you use int(i[-2]) to get the node label? For example, if the node label is 14, It will eventually be saved as 4.
I don't know the reason why you represent the node label in this way.
I would like to express my sincere thanks for your helping me out of my confusion!!

**Comment by ZhaoningYu1996** [comment]
Hi kmgrv,

I appreciate your interest in our project.
For node_labels, when we read files through f.readlines(), the entities in the list are each line with '\n' placeholder.
Thus, when we are creating node labels list, we remove '\n'.

Best,
Zhaoning

**Comment by Yang1806** [comment]
In the code there are some node labels are double digits, for example '14\n', if use int(i[-2]), we can only get the result of 4 instead of 14. Isn't the result of 14 is what we want?

**Comment by ZhaoningYu1996** [comment]
Hi,
Thank you for pointing it out.
We have fixed it, and you can directly use int(i) for node labels.
