### ISSUE TITLE
difference between h and h_pre

### ISSUE THREAD

**Issue by aliraza-ece** [ZhaoningYu1996/HM-GNN#8]
i'm a bit confused about `h` and `h_pre`
 https://github.com/ZhaoningYu1996/HM-GNN/blob/cdca83034097e2536cba5decc5b9517dbe9c3314/utils/gin.py#L172 
is `h_pre` atom-level information for molecular graphs
and `h` motif-level feature representations 

and what is the difference between `TwoGIN` and `ThreeGIN`? 

Thanks!

**Comment by ZhaoningYu1996** [comment]
Hi,

Thank you for your interest in our work.
Yes, h_pre is atom-level embedding, and h is motif-level embedding.
We are using TwoGIN in our experiments. ThreeGin is only for testing.

Feel free to let me know if there is any other questions.

Best

**Comment by aliraza-ece** [comment]
Thanks for getting back to me. 

I was doing some experiments to see the impact of h and h_pre. These are the results that I got for PTC dataset, seed = 0:
| method    | avg (std)    |
|-----------|--------------|
| h + h_pre | 75% (3)      |
| h_pre     | 72.39% (5.6) |
| h         | 70.59% (6.7) |

But h_pre is essentially GIN method and it should be around 64.4% according to table 3. 

<img width="437" alt="image" src="https://user-images.githubusercontent.com/48580833/236283986-a09dcf85-5642-45f3-9175-ddcbf910234b.png">

Am i missing something here?

**Comment by ZhaoningYu1996** [comment]
Yes, you are right. h_pre is the GIN method.
Given that the GIN we implemented exhibited improved performance on certain datasets while underperforming on others (83.5% on the MUTAG dataset), we present the accuracy reported in the original GIN publication.
